//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nestor.Tools.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Nestor.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessage() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nestor.Tools.Languages.ExceptionMessage", typeof(ExceptionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tout les flux doivent être accessibles en écriture..
        /// </summary>
        public static string AllStreamsMustBeWritable {
            get {
                return ResourceManager.GetString("AllStreamsMustBeWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le tableau de destination n&apos;est pas assez long. Vérifiez destIndex et la longueur, ainsi que les limites inférieures du tableau..
        /// </summary>
        public static string ArrayCapacityInsufficient {
            get {
                return ResourceManager.GetString("ArrayCapacityInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune propriété de l&apos;objet {0} ne comporte d&apos;attribut {1}.
        /// </summary>
        public static string AttributeUndefinedExceptionMessage {
            get {
                return ResourceManager.GetString("AttributeUndefinedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de la chaîne d&apos;entrée est incorrect..
        /// </summary>
        public static string BadInputStringFormat {
            get {
                return ResourceManager.GetString("BadInputStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La collection était de taille fixe.
        /// </summary>
        public static string CollectionFixedSize {
            get {
                return ResourceManager.GetString("CollectionFixedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La collection est en lecture seule..
        /// </summary>
        public static string CollectionIsReadOnly {
            get {
                return ResourceManager.GetString("CollectionIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le dictionnaire est en lecture seule..
        /// </summary>
        public static string DictionaryIsReadOnly {
            get {
                return ResourceManager.GetString("DictionaryIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;expression doit être un appel de méthode..
        /// </summary>
        public static string ExpressionMustBeMethodCall {
            get {
                return ResourceManager.GetString("ExpressionMustBeMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;expression doit être l&apos;accès à une propriété..
        /// </summary>
        public static string ExpressionMustBePropertyAccess {
            get {
                return ResourceManager.GetString("ExpressionMustBePropertyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom du fichier n&apos;est pas défini..
        /// </summary>
        public static string IniFileNameNotSet {
            get {
                return ResourceManager.GetString("IniFileNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La séquence d&apos;entrée contient plusieurs éléments..
        /// </summary>
        public static string InputSequenceHasMoreThanOneElement {
            get {
                return ResourceManager.GetString("InputSequenceHasMoreThanOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de convertir un objet null en un type valeur..
        /// </summary>
        public static string InvalidCastFromNullToValueType {
            get {
                return ResourceManager.GetString("InvalidCastFromNullToValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cast invalide de &apos;{0}&apos; en &apos;{1}&apos;..
        /// </summary>
        public static string InvalidCastFromTo {
            get {
                return ResourceManager.GetString("InvalidCastFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le NIR contient des caractères invalides. Il doit être composé de 13 chiffres à l&apos;exception du département qui peut être 2A ou 2B..
        /// </summary>
        public static string InvalidNir {
            get {
                return ResourceManager.GetString("InvalidNir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le caractère à convertir doit être une lettre entre A et Z..
        /// </summary>
        public static string InvalidRIBCharacter {
            get {
                return ResourceManager.GetString("InvalidRIBCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun fournisseur de devises disponible pour la culture &apos;{0}&apos;..
        /// </summary>
        public static string KnownCurrencies_NoProviderAvailable {
            get {
                return ResourceManager.GetString("KnownCurrencies_NoProviderAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les identifiants majeur, mineur et patch sont obligatoires..
        /// </summary>
        public static string MajorMinorPatchIdentifiersAreMandatory {
            get {
                return ResourceManager.GetString("MajorMinorPatchIdentifiersAreMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à maxLength ne peut pas être inférieur à {0}..
        /// </summary>
        public static string MaxLengthCantBeLessThan {
            get {
                return ResourceManager.GetString("MaxLengthCantBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à maxLength ne peut pas être inférieur à la longueur de ellipsisString..
        /// </summary>
        public static string MaxLengthCantBeLessThanLengthOfEllipsisString {
            get {
                return ResourceManager.GetString("MaxLengthCantBeLessThanLengthOfEllipsisString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre maximum de thread doit être supérieur ou égal à 1..
        /// </summary>
        public static string MaxThreadCountOutOfRange {
            get {
                return ResourceManager.GetString("MaxThreadCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;attribut Id est défini plusieurs fois pour l&apos;objet {0}..
        /// </summary>
        public static string MoreThanOneIdAttributeExceptionMessage {
            get {
                return ResourceManager.GetString("MoreThanOneIdAttributeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La durée de vie doit être strictement positive..
        /// </summary>
        public static string NegativeLifeTime {
            get {
                return ResourceManager.GetString("NegativeLifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun cas correspondant n&apos;a été trouvé.
        /// </summary>
        public static string NoMatchFound {
            get {
                return ResourceManager.GetString("NoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La liste ne contient aucun élément correspondant..
        /// </summary>
        public static string NoMatchingItemInList {
            get {
                return ResourceManager.GetString("NoMatchingItemInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun convertisseur disponible pour la culture &apos;{0}&apos;..
        /// </summary>
        public static string NumberConverter_NoSpellerAvailable {
            get {
                return ResourceManager.GetString("NumberConverter_NoSpellerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} doit être supérieur ou égal à zéro.
        /// </summary>
        public static string NumberMustBePositiveOrZero {
            get {
                return ResourceManager.GetString("NumberMustBePositiveOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} doit être strictement supérieur à zéro..
        /// </summary>
        public static string NumberMustBeStrictlyPositive {
            get {
                return ResourceManager.GetString("NumberMustBeStrictlyPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seuls les types numériques sont supportés.
        /// </summary>
        public static string OnlyNumericTypesAreSupported {
            get {
                return ResourceManager.GetString("OnlyNumericTypesAreSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le temps imparti à l&apos;opération est écoulé..
        /// </summary>
        public static string OperationTimedOut {
            get {
                return ResourceManager.GetString("OperationTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La partie pre-release doit être avant la partie build..
        /// </summary>
        public static string PreReleasePartMustBeBeforeBuildPart {
            get {
                return ResourceManager.GetString("PreReleasePartMustBeBeforeBuildPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un nombre en chiffres romains ne peut pas être supérieur à {0}..
        /// </summary>
        public static string RomanMaxValue {
            get {
                return ResourceManager.GetString("RomanMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un nombre en chiffres romains ne peut pas être inférieur à {0}..
        /// </summary>
        public static string RomanMinValue {
            get {
                return ResourceManager.GetString("RomanMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La séquence ne contient aucun élément..
        /// </summary>
        public static string SequenceContainsNoElements {
            get {
                return ResourceManager.GetString("SequenceContainsNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La chaîne de caractères doit représenter un nombre..
        /// </summary>
        public static string StringNotANumber {
            get {
                return ResourceManager.GetString("StringNotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La chaîne de caractères ne doit pas être vide..
        /// </summary>
        public static string StringNullOrEmpty {
            get {
                return ResourceManager.GetString("StringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La chaîne doit faire {0} caractères de long..
        /// </summary>
        public static string StringWrongLength {
            get {
                return ResourceManager.GetString("StringWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre de caractères doit être supérieur ou égal à zéro et inférieur ou égal à la longueur de la chaine.
        /// </summary>
        public static string SubstringCountOutOfRange {
            get {
                return ResourceManager.GetString("SubstringCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune valeur trouvée pour la clé &apos;{0}&apos;..
        /// </summary>
        public static string TemplateKeyNotFound {
            get {
                return ResourceManager.GetString("TemplateKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le timeout doit être supérieur ou égal à 1 milliseconde..
        /// </summary>
        public static string TimeoutOutOfRange {
            get {
                return ResourceManager.GetString("TimeoutOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type &apos;{0}&apos; n&apos;implémente pas l&apos;évènement &apos;{1}&apos;..
        /// </summary>
        public static string TypeDoesntImplementEvent {
            get {
                return ResourceManager.GetString("TypeDoesntImplementEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type &apos;{0}&apos; n&apos;est pas une énumération..
        /// </summary>
        public static string TypeIsNotEnum {
            get {
                return ResourceManager.GetString("TypeIsNotEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type &apos;{0}&apos; n&apos;a pas l&apos;attribut System.FlagsAttribute..
        /// </summary>
        public static string TypeNotDecoratedWithFlags {
            get {
                return ResourceManager.GetString("TypeNotDecoratedWithFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de conversion inconnu..
        /// </summary>
        public static string UnknownConversionType {
            get {
                return ResourceManager.GetString("UnknownConversionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le wrapper a été fermé..
        /// </summary>
        public static string WrapperClosed {
            get {
                return ResourceManager.GetString("WrapperClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zéro n&apos;a pas d&apos;adjectif numéral ordinal..
        /// </summary>
        public static string ZeroHasNoOrdinal {
            get {
                return ResourceManager.GetString("ZeroHasNoOrdinal", resourceCulture);
            }
        }
    }
}
