name: Build-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Nestor.sln'
      
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.1.1
        
      - name: Restore dependencies
        run: nuget restore $SOLUTION
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: 3.1.x
          
      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore    
      
