name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Nestor.sln'
  
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
    - name: Restore dependencies
      run: dotnet restore $SOLUTION   
    - name: Install dotnet tool
      run: dotnet tool install -g dotnetCampus.TagToVersion
    - name: Set tag to version # https://medium.com/@lindexi_gd/how-to-generate-nuget-package-with-git-tag-version-using-github-action-207ff4040486
      run: dotnet TagToVersion -t ${{ github.ref }}
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
    - name: Pack nugets
      run: dotnet pack -c Release --no-build --output .
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
